### PR TITLE
Clear source; Fix wanings; unified build

### PR DESCRIPTION
**Pull request by ghost**
- Remove all bin
- Fix warnings
- Setup cross compiler full dependency
- Unic build.sh, compile dlr, loader, cnc, scanList, etc..
- Add gitignore to prevent output and bin
- Update README, add Setup Cross-Compiler and Build
## Format output

build.sh create new folder in compiler

```
output
 |-- Release
 |         |-- loader
 |         |      |-- bins
 |         |-- mirai
 |                |-- telnet
 |                |-- ssh
 |-- debug
           |-- loader
           |      |-- bins
           |-- mirai
                  |-- telnet
                  |-- ssh
```

### CODE REVIEW

**Comment by samrocketman** [comment]
👎 this includes binaries.  We should not be including binaries with the source IMO.  That's what GitHub releases are for.

e.g. `loader/bins/*`.

**Comment by samrocketman** [comment]
This drastically changes the original release as well.  I think the intent of this project is to preserve the original source for study.  Not to be an actively maintained project with up-to-date build scripts.

**Comment by samrocketman** [comment]
I also recommend squashing this into a single commit so it's easier to review.

**Comment by jgamblin** [comment]
@NoxxDev I am done updating this repo.  I think this as close to original as I can get and my goal was to put the original code up for study.

**Pull request closed without merging**
